version: '2'

services:

### Mount Applications ######################################

    applications:
        image: tianon/true
        volumes:
            - ./:/var/www/html/demo3

### Buphalo Container (php-fpm) #########################

    demo3:
        build:
            context: .
            args:
                - COMPOSER_TOKEN=9f506692cafe6be658ce31bcd5e2a481ffb5e884
                - INSTALL_XDEBUG=true
                - COMPOSER_INSTALL=false
        volumes_from:
            - applications
        expose:
            - "9002"
        environment:
            PHP_IDE_CONFIG: "serverName=demo3.buphalofitness.neighborhoods.com"
